### ISSUE TITLE
Change Copulas : None into Copula : Independent

### ISSUE THREAD

**Issue by regislebrun** [damar-wicaksono/uqtestfuns#317]
According to Sklar's theorem (https://en.wikipedia.org/wiki/Copula_(probability_theory)#Sklar's_theorem), there exists a unique copula for joint distributios with continuous marginal distributions. As a consequence, copulas should be changed into copula, and can never be None, even in the independent case.

Cheers

**Comment by damar-wicaksono** [comment]
@regislebrun: Indeed[^1]! Thank you very much for pointing that out!

[^1]: although as an instance in the code it is the Python `None` 😄

**Comment by damar-wicaksono** [comment]
This issue has been temporarily resolved by PR #390.
